name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for git describe

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        python3 --version
        curl -sSL https://install.python-poetry.org | python3 - --version 2.1.2
        poetry --version

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install

    - name: Run pre-commit hooks
      run: poetry run pre-commit run --all-files

    - name: Run tests
      run: poetry run pytest tests/

    - name: Test version with git tag
      run: |
        git tag -a v99.98.96 -m "Test version"
        VERSION=$(poetry run python -c "from hello_world import __version__; print(__version__)")
        if [ "$VERSION" != "v99.98.97" ]; then
          echo "Version mismatch. Expected v99.98.97, got $VERSION"
          exit 1
        fi

    - name: Test version with distance
      run: |
        echo "Making a commit to create distance from tag" > test.txt
        git add test.txt
        git commit -m "Test commit"
        VERSION=$(poetry run python -c "from hello_world import __version__; print(__version__)")
        if [[ ! "$VERSION" =~ ^v99\.98\.97\+[0-9]+$ ]]; then
          echo "Version mismatch. Expected v99.98.97+<number>, got $VERSION"
          exit 1
        fi

    - name: Test version without git tag
      run: |
        git tag -d v99.98.97
        VERSION=$(poetry run python -c "from hello_world import __version__; print(__version__)")
        if [ "$VERSION" != "0.0.0+placeholder" ]; then
          echo "Version mismatch. Expected 0.0.0+placeholder, got $VERSION"
          exit 1
        fi
